events {}

http {
  server {
    listen       8443 ssl;
    server_name  localhost;

    ssl_certificate      /Users/dpalm/labs/tls-lab/certs/svc.crt;
    ssl_certificate_key  /Users/dpalm/labs/tls-lab/certs/svc.key;

    ssl_client_certificate /Users/dpalm/labs/tls-lab/ca/certs/root_ca.crt;
    ssl_verify_client      on;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
      return 200 'mTLS working! Client: $ssl_client_s_dn\n';
      add_header Content-Type text/plain;
    }
  }
}
